version: '3'

services:
  nginx:
    image: nginx:1.17.6
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`boum.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    volumes:
      - ./src/public:/usr/share/nginx/html:ro
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro

  php:
    build: .
    volumes:
      - ./src:/usr/local/src

  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    image: traefik:2.0.4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.boum.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
